spring:
  jpa:
    hibernate.ddl-auto: create
    #show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  datasource:
    driver-class-name: com.mysql.jdbc.Driver  #apparently driver is auto-loaded and this is deprecated
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}

stripe:
  apiKey: ${STRIPE_API_SECRET_KEY}
  webhookSecret: ${STRIPE_WEBHOOK_SECRET}

amazon:
    accessKey: ${AWS_ACCESS_KEY}
    secretKey: ${AWS_SECRET_KEY}
    s3:
      region: "eu-central-1"
      bucketName: "imagestoragetest"


